worker_processes 1;
pid ./test-fixtures/nginx/nginx.pid;
events { worker_connections 128; }
http {
    include       mime.types;
    default_type  application/octet-stream;
    include ./test-fixtures/nginx/conf.d/*.conf;
    include ./test-fixtures/nginx/domains-enabled/*/root.conf;
    include ./test-fixtures/nginx/domains-enabled/*/subdomains-enabled/*.conf;
}
