worker_processes 1;
pid ../../var/run/nginx.pid;
events { worker_connections 128; }
http {
    include       mime.types;
    default_type  application/octet-stream;
    include conf.d/*.conf;
    include domains-enabled/*/root.conf;
    include domains-enabled/*/subdomains-enabled/*.conf;
}
