#!/bin/sh

ENABLED=yes
PROCS=router-hub
ARGS=""
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

if [ "${1:-}" = "reconcile" ]; then
    PID="$(pidof "$PROCS" 2>/dev/null || true)"
    [ -n "$PID" ] || exit 1
    for process_id in $PID; do
        kill -USR1 "$process_id"
    done
    exit 0
fi

. /opt/etc/init.d/rc.func
